# Travis CI settings

language: python

python:
  - '3.4'

env:
  matrix:
    - DB=sqlite DJANGO_VERSION=1.9.6

install:
  - pip install -U pip
  - pip install -r requirements.txt

before_script:

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - export SECRET_KEY="78m5@7^h(lne^@08$0@dn5i%96v^*u@v+1zp9_5t!iagf5319v"
  - python3 bike_store/manage.py migrate
  - sleep 3

script:
  - python3 bike_store/manage.py test store
  - python3 -m pylint mysite/store/